super_block = {
  's_inodes_count': {'offset': 0x0, 'size': 4, 'byteorder': 'little'},
  's_blocks_count_lo': {'offset': 0x4, 'size': 4, 'byteorder': 'little'},
  's_r_blocks_count_lo': {'offset': 0x8, 'size': 4, 'byteorder': 'little'},
  's_free_blocks_count_lo': {'offset': 0xC, 'size': 4, 'byteorder': 'little'},
  's_free_inodes_count': {'offset': 0x10, 'size': 4, 'byteorder': 'little'},
  's_first_data_block': {'offset': 0x14, 'size': 4, 'byteorder': 'little'},
  's_log_block_size': {'offset': 0x18, 'size': 4, 'byteorder': 'little'},
  's_log_cluster_size': {'offset': 0x1C, 'size': 4, 'byteorder': 'little'},
  's_blocks_per_group': {'offset': 0x20, 'size': 4, 'byteorder': 'little'},
  's_clusters_per_group': {'offset': 0x24, 'size': 4, 'byteorder': 'little'},
  's_inodes_per_group': {'offset': 0x28, 'size': 4, 'byteorder': 'little'},
  's_mtime': {'offset': 0x2C, 'size': 4, 'byteorder': 'little'},
  's_wtime': {'offset': 0x30, 'size': 4, 'byteorder': 'little'},
  's_mnt_count': {'offset': 0x34, 'size': 2, 'byteorder': 'little'},
  's_max_mnt_count': {'offset': 0x36, 'size': 2, 'byteorder': 'little'},
  's_magic': {'offset': 0x38, 'size': 2, 'byteorder': 'little'},
  's_state': {'offset': 0x3A, 'size': 2, 'byteorder': 'little'},
  's_errors': {'offset': 0x3C, 'size': 2, 'byteorder': 'little'},
  's_minor_rev_level': {'offset': 0x3E, 'size': 2, 'byteorder': 'little'},
  's_lastcheck': {'offset': 0x40, 'size': 4, 'byteorder': 'little'},
  's_checkinterval': {'offset': 0x44, 'size': 4, 'byteorder': 'little'},
  's_creator_os': {'offset': 0x48, 'size': 4, 'byteorder': 'little'},
  's_rev_level': {'offset': 0x4C, 'size': 4, 'byteorder': 'little'},
  's_def_resuid': {'offset': 0x50, 'size': 2, 'byteorder': 'little'},
  's_def_resgid': {'offset': 0x52, 'size': 2, 'byteorder': 'little'},
  's_first_ino': {'offset': 0x54, 'size': 4, 'byteorder': 'little'},
  's_inode_size': {'offset': 0x58, 'size': 2, 'byteorder': 'little'},
  's_block_group_nr': {'offset': 0x5A, 'size': 2, 'byteorder': 'little'},
  's_feature_compat': {'offset': 0x5C, 'size': 4, 'byteorder': 'little'},
  's_feature_incompat': {'offset': 0x60, 'size': 4, 'byteorder': 'little'},
  's_feature_ro_compat': {'offset': 0x64, 'size': 4, 'byteorder': 'little'},
  's_uuid[16]': {'offset': 0x68, 'size': 1, 'byteorder': 'big'},
  's_volume_name[16]': {'offset': 0x78, 'size': 1, 'byteorder': 'big'},  # CHAR
  's_last_mounted[64]': {'offset': 0x88, 'size': 1, 'byteorder': 'big'},  # CHAR
  's_algorithm_usage_bitmap': {'offset': 0xC8, 'size': 4, 'byteorder': 'little'},
  's_prealloc_blocks': {'offset': 0xCC, 'size': 1, 'byteorder': 'big'},
  's_prealloc_dir_blocks': {'offset': 0xCD, 'size': 1, 'byteorder': 'big'},
  's_reserved_gdt_blocks': {'offset': 0xCE, 'size': 2, 'byteorder': 'little'},
  's_journal_uuid[16]': {'offset': 0xD0, 'size': 1, 'byteorder': 'big'},
  's_journal_inum': {'offset': 0xE0, 'size': 4, 'byteorder': 'little'},
  's_journal_dev': {'offset': 0xE4, 'size': 4, 'byteorder': 'little'},
  's_last_orphan': {'offset': 0xE8, 'size': 4, 'byteorder': 'little'},
  's_hash_seed[4]': {'offset': 0xEC, 'size': 4, 'byteorder': 'little'},
  's_def_hash_version': {'offset': 0xFC, 'size': 1, 'byteorder': 'big'},
  's_jnl_backup_type': {'offset': 0xFD, 'size': 1, 'byteorder': 'big'},
  's_desc_size': {'offset': 0xFE, 'size': 2, 'byteorder': 'little'},
  's_default_mount_opts': {'offset': 0x100, 'size': 4, 'byteorder': 'little'},
  's_first_meta_bg': {'offset': 0x104, 'size': 4, 'byteorder': 'little'},
  's_mkfs_time': {'offset': 0x108, 'size': 4, 'byteorder': 'little'},
  's_jnl_blocks[17]': {'offset': 0x10C, 'size': 4, 'byteorder': 'little'},
  's_blocks_count_hi': {'offset': 0x150, 'size': 4, 'byteorder': 'little'},
  's_r_blocks_count_hi': {'offset': 0x154, 'size': 4, 'byteorder': 'little'},
  's_free_blocks_count_hi': {'offset': 0x158, 'size': 4, 'byteorder': 'little'},
  's_min_extra_isize': {'offset': 0x15C, 'size': 2, 'byteorder': 'little'},
  's_want_extra_isize': {'offset': 0x15E, 'size': 2, 'byteorder': 'little'},
  's_flags': {'offset': 0x160, 'size': 4, 'byteorder': 'little'},
  's_raid_stride': {'offset': 0x164, 'size': 2, 'byteorder': 'little'},
  's_mmp_interval': {'offset': 0x166, 'size': 2, 'byteorder': 'little'},
  's_mmp_block': {'offset': 0x168, 'size': 8, 'byteorder': 'little'},
  's_raid_stripe_width': {'offset': 0x170, 'size': 4, 'byteorder': 'little'},
  's_log_groups_per_flex': {'offset': 0x174, 'size': 1, 'byteorder': 'big'},
  's_checksum_type': {'offset': 0x175, 'size': 1, 'byteorder': 'big'},
  's_reserved_pad': {'offset': 0x176, 'size': 2, 'byteorder': 'little'},
  's_kbytes_written': {'offset': 0x178, 'size': 8, 'byteorder': 'little'},
  's_snapshot_inum': {'offset': 0x180, 'size': 4, 'byteorder': 'little'},
  's_snapshot_id': {'offset': 0x184, 'size': 4, 'byteorder': 'little'},
  's_snapshot_r_blocks_count': {'offset': 0x188, 'size': 8, 'byteorder': 'little'},
  's_snapshot_list': {'offset': 0x190, 'size': 4, 'byteorder': 'little'},
  's_error_count': {'offset': 0x194, 'size': 4, 'byteorder': 'little'},
  's_first_error_time': {'offset': 0x198, 'size': 4, 'byteorder': 'little'},
  's_first_error_ino': {'offset': 0x19C, 'size': 4, 'byteorder': 'little'},
  's_first_error_block': {'offset': 0x1A0, 'size': 8, 'byteorder': 'little'},
  's_first_error_func[32]': {'offset': 0x1A8, 'size': 1, 'byteorder': 'big'},
  's_first_error_line': {'offset': 0x1C8, 'size': 4, 'byteorder': 'little'},
  's_last_error_time': {'offset': 0x1CC, 'size': 4, 'byteorder': 'little'},
  's_last_error_ino': {'offset': 0x1D0, 'size': 4, 'byteorder': 'little'},
  's_last_error_line': {'offset': 0x1D4, 'size': 4, 'byteorder': 'little'},
  's_last_error_block': {'offset': 0x1D8, 'size': 8, 'byteorder': 'little'},
  's_last_error_func[32]': {'offset': 0x1E0, 'size': 1, 'byteorder': 'big'},
  's_mount_opts[64]': {'offset': 0x200, 'size': 1, 'byteorder': 'big'},
  's_usr_quota_inum': {'offset': 0x240, 'size': 4, 'byteorder': 'little'},
  's_grp_quota_inum': {'offset': 0x244, 'size': 4, 'byteorder': 'little'},
  's_overhead_blocks': {'offset': 0x248, 'size': 4, 'byteorder': 'little'},
  's_backup_bgs[2]': {'offset': 0x24C, 'size': 4, 'byteorder': 'little'},
  's_encrypt_algos[4]': {'offset': 0x254, 'size': 1, 'byteorder': 'big'},
  's_encrypt_pw_salt[16]': {'offset': 0x258, 'size': 1, 'byteorder': 'big'},
  's_lpf_ino': {'offset': 0x268, 'size': 4, 'byteorder': 'little'},
  's_prj_quota_inum': {'offset': 0x26C, 'size': 4, 'byteorder': 'little'},
  's_checksum_seed': {'offset': 0x270, 'size': 4, 'byteorder': 'little'},
  's_wtime_hi': {'offset': 0x274, 'size': 1, 'byteorder': 'big'},
  's_mtime_hi': {'offset': 0x275, 'size': 1, 'byteorder': 'big'},
  's_mkfs_time_hi': {'offset': 0x276, 'size': 1, 'byteorder': 'big'},
  's_lastcheck_hi': {'offset': 0x277, 'size': 1, 'byteorder': 'big'},
  's_first_error_time_hi': {'offset': 0x278, 'size': 1, 'byteorder': 'big'},
  's_last_error_time_hi': {'offset': 0x279, 'size': 1, 'byteorder': 'big'},
  's_pad[2]': {'offset': 0x27A, 'size': 1, 'byteorder': 'big'},
  's_encoding': {'offset': 0x27C, 'size': 2, 'byteorder': 'little'},
  's_encoding_flags': {'offset': 0x27E, 'size': 2, 'byteorder': 'little'},
  's_orphan_file_inum': {'offset': 0x280, 'size': 4, 'byteorder': 'little'},
  's_reserved[94]': {'offset': 0x284, 'size': 4, 'byteorder': 'little'},
  's_checksum': {'offset': 0x3FC, 'size': 4, 'byteorder': 'little'}
}

group_desc = {
  'bg_block_bitmap_lo': {'offset': 0x0, 'size': 4, 'byteorder': 'little'},
  'bg_inode_bitmap_lo': {'offset': 0x4, 'size': 4, 'byteorder': 'little'},
  'bg_inode_table_lo': {'offset': 0x8, 'size': 4, 'byteorder': 'little'},
  'bg_free_blocks_count_lo': {'offset': 0xC, 'size': 2, 'byteorder': 'little'},
  'bg_free_inodes_count_lo': {'offset': 0xE, 'size': 2, 'byteorder': 'little'},
  'bg_used_dirs_count_lo': {'offset': 0x10, 'size': 2, 'byteorder': 'little'},
  'bg_flags': {'offset': 0x12, 'size': 2, 'byteorder': 'little'},
  'bg_exclude_bitmap_lo': {'offset': 0x14, 'size': 4, 'byteorder': 'little'},
  'bg_block_bitmap_csum_lo': {'offset': 0x18, 'size': 2, 'byteorder': 'little'},
  'bg_inode_bitmap_csum_lo': {'offset': 0x1A, 'size': 2, 'byteorder': 'little'},
  'bg_itable_unused_lo': {'offset': 0xC, 'size': 2, 'byteorder': 'little'},
  'bg_checksum': {'offset': 0x1E, 'size': 2, 'byteorder': 'little'},
  'bg_block_bitmap_hi': {'offset': 0x20, 'size': 4, 'byteorder': 'little'},
  'bg_inode_bitmap_hi': {'offset': 0x24, 'size': 4, 'byteorder': 'little'},
  'bg_inode_table_hi': {'offset': 0x28, 'size': 4, 'byteorder': 'little'},
  'bg_free_blocks_count_hi': {'offset': 0x2C, 'size': 2, 'byteorder': 'little'},
  'bg_free_inodes_count_hi': {'offset': 0x2E, 'size': 2, 'byteorder': 'little'},
  'bg_used_dirs_count_hi': {'offset': 0x30, 'size': 2, 'byteorder': 'little'},
  'bg_itable_unused_hi': {'offset': 0x32, 'size': 2, 'byteorder': 'little'},
  'bg_exclude_bitmap_hi': {'offset': 0x34, 'size': 4, 'byteorder': 'little'},
  'bg_block_bitmap_csum_hi': {'offset': 0x38, 'size': 2, 'byteorder': 'little'},
  'bg_inode_bitmap_csum_hi': {'offset': 0x3A, 'size': 2, 'byteorder': 'little'},
  'bg_reserved': {'offset': 0x3C, 'size': 4, 'byteorder': 'big'}
}

inode = {
  'i_mode': {'offset': 0x0, 'size': 2, 'byteorder': 'little'},
  'i_uid': {'offset': 0x2, 'size': 2, 'byteorder': 'little'},
  'i_size': {'offset': 0x4, 'size': 4, 'byteorder': 'little'},
  'i_atime': {'offset': 0x8, 'size': 4, 'byteorder': 'little'},
  'i_ctime': {'offset': 0xC, 'size': 4, 'byteorder': 'little'},
  'i_mtime': {'offset': 0x10, 'size': 4, 'byteorder': 'little'},
  'i_dtime': {'offset': 0x14, 'size': 4, 'byteorder': 'little'},
  'i_gid': {'offset': 0x18, 'size': 2, 'byteorder': 'little'},
  'i_links_count': {'offset': 0x1A, 'size': 2, 'byteorder': 'little'},
  'i_blocks': {'offset': 0x1C, 'size': 4, 'byteorder': 'little'},
  'i_flags': {'offset': 0x20, 'size': 4, 'byteorder': 'little'},
  'i_osd1': {'offset': 0x24, 'size': 4, 'byteorder': 'little'},  #
  'i_block[15]': {'offset': 0x28, 'size': 4, 'byteorder': 'little'},  ### LE???? 60 15 блоков по 4 байта, исправить
  'i_generation': {'offset': 0x64, 'size': 4, 'byteorder': 'little'},  # список читается как BE
  'i_file_acl': {'offset': 0x68, 'size': 4, 'byteorder': 'little'},    # элементы в LE
  'i_dir_acl': {'offset': 0x6C, 'size': 4, 'byteorder': 'little'},
  'i_faddr': {'offset': 0x70, 'size': 4, 'byteorder': 'little'},
  'i_osd2[12]': {'offset': 0x74, 'size': 12, 'byteorder': 'little'},  #
  'i_extra_isize': {'offset': 0x80, 'size': 2, 'byteorder': 'little'},
  'i_checksum_hi': {'offset': 0x82, 'size': 2, 'byteorder': 'little'},
  'i_ctime_extra': {'offset': 0x84, 'size': 4, 'byteorder': 'little'},
  'i_mtime_extra': {'offset': 0x88, 'size': 4, 'byteorder': 'little'},
  'i_atime_extra': {'offset': 0x8C, 'size': 4, 'byteorder': 'little'},
  'i_crtime': {'offset': 0x90, 'size': 4, 'byteorder': 'little'},
  'i_crtime_extra': {'offset': 0x94, 'size': 4, 'byteorder': 'little'},
  'i_version_hi': {'offset': 0x98, 'size': 4, 'byteorder': 'little'},
  'i_projid': {'offset': 0x9C, 'size': 4, 'byteorder': 'little'}
}

file_acl = {
  'ext4_xattr_header': {
    'h_magic': {'offset': 0x0, 'size': 4, 'byteorder': 'little'},
    'h_refcount': {'offset': 0x4, 'size': 4, 'byteorder': 'little'},
    'h_blocks': {'offset': 0x8, 'size': 4, 'byteorder': 'little'},
    'h_hash': {'offset': 0xC, 'size': 4, 'byteorder': 'little'},
    'h_checksum': {'offset': 0x10, 'size': 4, 'byteorder': 'little'},
    'h_reserved': {'offset': 0x14, 'size': 8, 'byteorder': 'big'},
  },
  'ext4_xattr_entry': {
      'e_name_len': {'offset': 0x0, 'size': 1, 'byteorder': 'big'},
      'e_name_index': {'offset': 0x1, 'size': 1, 'byteorder': 'big'},
      'e_value_offs': {'offset': 0x2, 'size': 2, 'byteorder': 'little'},
      'e_value_inum': {'offset': 0x4, 'size': 4, 'byteorder': 'little'},
      'e_value_size': {'offset': 0x8, 'size': 4, 'byteorder': 'little'},
      'e_hash': {'offset': 0xC, 'size': 4, 'byteorder': 'little'},
      # 'e_name': {'offset': 0x30, 'size': 4, 'byteorder': 'big'}  # зависит от e_name_len, вычисляется в main
    }
}
